const state={snapshot:[],sales:[],filtered:[]};
const fmtInt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n||0);
const fmtMoney=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'SAR',maximumFractionDigits:0}).format(n||0);
const parseCSV=t=>{const lines=t.trim().split(/\r?\n/);const h=lines.shift().split(',');return lines.map(line=>{let out=[],cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===','&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return Object.fromEntries(h.map((k,i)=>[k,out[i]??'']))})};
const num=(v)=>v===''||v==null?0:Number(v);
async function load(){const [a,b]=await Promise.all([fetch('data/sample_inventory_snapshot.csv').then(r=>r.text()),fetch('data/sample_sales_90_days.csv').then(r=>r.text())]);state.snapshot=parseCSV(a).map(r=>({...r,product_id:num(r.product_id),retail_price_sar:num(r.retail_price_sar),stock_qty:num(r.stock_qty),sales_90d_qty:num(r.sales_90d_qty),sales_value_90d_sar:num(r.sales_value_90d_sar),avg_daily_units:num(r.avg_daily_units),stock_cover_days:r.stock_cover_days===''?null:num(r.stock_cover_days),inventory_value_sar:num(r.inventory_value_sar),expired_units:num(r.expired_units),units_expiring_30d:num(r.units_expiring_30d),dead_stock_flag:num(r.dead_stock_flag),slow_moving_flag:num(r.slow_moving_flag),reorder_candidate_flag:num(r.reorder_candidate_flag),reorder_qty_30d:num(r.reorder_qty_30d)}));state.sales=parseCSV(b).map(r=>({...r,product_id:num(r.product_id),quantity:num(r.quantity)}));initFilters();apply();}
function initFilters(){const cats=[...new Set(state.snapshot.map(r=>r.category))].sort();categoryFilter.innerHTML='<option value="ALL">All categories</option>'+cats.map(x=>`<option>${x}</option>`).join('');updateSubs();categoryFilter.onchange=()=>{updateSubs();apply()};subFilter.onchange=apply;statusFilter.onchange=apply;resetBtn.onclick=()=>{categoryFilter.value='ALL';updateSubs();statusFilter.value='ALL';apply()}}
function updateSubs(){const cat=categoryFilter.value;const subs=[...new Set(state.snapshot.filter(r=>cat==='ALL'||r.category===cat).map(r=>r.sub_category))].sort();subFilter.innerHTML='<option value="ALL">All subcategories</option>'+subs.map(x=>`<option>${x}</option>`).join('')}
function apply(){const c=categoryFilter.value,s=subFilter.value,v=statusFilter.value;state.filtered=state.snapshot.filter(r=>(c==='ALL'||r.category===c)&&(s==='ALL'||r.sub_category===s)&&(v==='ALL'||(v==='REORDER'&&r.reorder_candidate_flag)||(v==='EXPIRY'&&(r.expired_units+r.units_expiring_30d)>0)||(v==='DEAD'&&r.dead_stock_flag)||(v==='SLOW'&&r.slow_moving_flag)));render()}
function render(){renderKPIs();renderCategory();renderRisk();renderTrend();renderCoverage();renderTables()}
function renderKPIs(){const d=state.filtered;const vals=[['SKUs in View',d.length,'filtered products'],['Stock Units',d.reduce((a,r)=>a+r.stock_qty,0),'on-hand units'],['Inventory Value',fmtMoney(d.reduce((a,r)=>a+r.inventory_value_sar,0)),'retail value'],['90-Day Sales',d.reduce((a,r)=>a+r.sales_90d_qty,0),'units sold'],['Expiry Risk Units',d.reduce((a,r)=>a+r.expired_units+r.units_expiring_30d,0),'expired or ≤30 days'],['Dead Stock Value',fmtMoney(d.filter(r=>r.dead_stock_flag).reduce((a,r)=>a+r.inventory_value_sar,0)),'stock with zero 90d sales']];kpis.innerHTML=vals.map(([l,v,h])=>`<article class="card kpi"><div class="label">${l}</div><div class="value">${typeof v==='number'?fmtInt(v):v}</div><div class="hint">${h}</div></article>`).join('')}
function renderCategory(){const m={};state.filtered.forEach(r=>m[r.category]=(m[r.category]||0)+r.inventory_value_sar);const arr=Object.entries(m).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...arr.map(x=>x[1]));categoryChart.innerHTML=arr.length?arr.map(([k,v])=>`<div class="bar-row"><div class="bar-label" title="${k}">${k}</div><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><div class="bar-value">${fmtMoney(v)}</div></div>`).join(''):'<p>No data for current filters.</p>'}
function renderRisk(){const d=state.filtered;const arr=[['Expiry risk',d.filter(r=>r.expired_units+r.units_expiring_30d>0).length],['Dead stock',d.filter(r=>r.dead_stock_flag).length],['Slow moving',d.filter(r=>r.slow_moving_flag).length],['Reorder',d.filter(r=>r.reorder_candidate_flag).length]];const max=Math.max(1,...arr.map(x=>x[1]));riskChart.innerHTML=`<div class="risk-list">${arr.map(([k,v])=>`<div class="risk-item"><span>${k}</span><div class="risk-dot"><span style="width:${v/max*100}%"></span></div><strong>${v}</strong></div>`).join('')}</div>`}
function renderTrend(){const ids=new Set(state.filtered.map(r=>r.product_id));const m={};state.sales.forEach(r=>{if(ids.has(r.product_id))m[r.date]=(m[r.date]||0)+r.quantity});const pts=Object.entries(m).sort();if(!pts.length){trendChart.innerHTML='<p>No data for current filters.</p>';return}const W=760,H=230,pad=26,max=Math.max(1,...pts.map(x=>x[1]));const xy=pts.map((x,i)=>[pad+i*(W-2*pad)/(pts.length-1),H-pad-x[1]*(H-2*pad)/max]);const path=xy.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+','+p[1].toFixed(1)).join(' ');const area=`M${xy[0][0]},${H-pad} `+xy.map(p=>`L${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(' ')+` L${xy.at(-1)[0]},${H-pad} Z`;trendChart.innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><line class="axis" x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}"/><path class="area" d="${area}"/><path class="line" d="${path}"/></svg>`}
function renderCoverage(){const buckets={'<14 days':0,'14–30 days':0,'31–90 days':0,'91–120 days':0,'>120 days':0};state.filtered.filter(r=>r.stock_cover_days!==null).forEach(r=>{const x=r.stock_cover_days;if(x<14)buckets['<14 days']++;else if(x<=30)buckets['14–30 days']++;else if(x<=90)buckets['31–90 days']++;else if(x<=120)buckets['91–120 days']++;else buckets['>120 days']++});const arr=Object.entries(buckets);const max=Math.max(1,...arr.map(x=>x[1]));coverageChart.innerHTML=arr.map(([k,v])=>`<div class="bar-row"><div class="bar-label">${k}</div><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><div class="bar-value">${v}</div></div>`).join('')}
function renderTables(){const re=[...state.filtered].filter(r=>r.reorder_candidate_flag).sort((a,b)=>(a.stock_cover_days??999)-(b.stock_cover_days??999)).slice(0,12);reorderTable.innerHTML=re.length?re.map(r=>`<tr><td>${r.item_code}</td><td>${r.category}</td><td>${r.stock_qty}</td><td>${r.sales_90d_qty}</td><td>${r.stock_cover_days?.toFixed(1)??'N/A'}</td><td>${r.reorder_qty_30d}</td></tr>`).join(''):'<tr><td colspan="6">No reorder candidates in current view.</td></tr>';const risk=[...state.filtered].filter(r=>r.dead_stock_flag||r.expired_units+r.units_expiring_30d>0).sort((a,b)=>(b.expired_units+b.units_expiring_30d)-(a.expired_units+a.units_expiring_30d)||b.inventory_value_sar-a.inventory_value_sar).slice(0,12);riskTable.innerHTML=risk.length?risk.map(r=>`<tr><td>${r.item_code}</td><td>${r.category}</td><td>${r.stock_qty}</td><td>${r.expired_units+r.units_expiring_30d}</td><td>${r.dead_stock_flag?fmtMoney(r.inventory_value_sar):'—'}</td><td>${r.nearest_expiry_date||'N/A'}</td></tr>`).join(''):'<tr><td colspan="6">No flagged products in current view.</td></tr>'}
load().catch(e=>{document.querySelector('main').insertAdjacentHTML('afterbegin',`<div class="card" style="padding:18px;color:#a22">Dashboard data could not be loaded. Run the project through a local HTTP server as described in README.md.<br><small>${e}</small></div>`)})
